pipeline {
    agent {
        label 'java-docker-slave'
        // docker {
        //     image 'maven:3.9.0'
        //     args '-v /root/.m2:/root/.m2'
        // }
    }
    stages {
        stage('Build') {
            steps {
                sh ''' 
                    echo "updating Maven version"
                    cd /tmp
                    wget https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz
                    tar xvf apache-maven-3.8.5-bin.tar.gz 
                    cd /usr/share/maven 
                    sudo cp /tmp/apache-maven-3.8.5/* .
                    mvn -version
                '''
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
